const $=selector=>document.querySelector(selector);let challenge=null;let phone=null;
async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",...options,headers:{...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})}});if(response.status===204)return null;const value=await response.json();if(!response.ok)throw new Error(value.error?.code||"temporarily_unavailable");return value}
function show(authenticated){$("#auth-view").hidden=authenticated;$("#workbench-view").hidden=!authenticated;document.querySelector(".sidebar").hidden=!authenticated;document.querySelector(".bottom-nav").hidden=!authenticated}
function status(target,message,error=false){target.textContent=message;target.classList.toggle("error",error)}
async function refresh(){try{await api("/v1/session");show(true);const data=await api("/v1/workbench");$("#error-count").textContent=data.error_count;$("#task-count").textContent=data.pending_task_count;const list=$("#error-list");list.innerHTML=data.recent_errors.length?data.recent_errors.map(item=>`<li><strong>${escapeHtml(item.question_text)}</strong><br><small>${escapeHtml(item.first_error||"待整理错因")}</small></li>`).join(""):'<li class="empty">还没有错题，上传第一道题吧。</li>'}catch{show(false)}}
function escapeHtml(value){const span=document.createElement("span");span.textContent=value;return span.innerHTML}
$("#phone-form").addEventListener("submit",async event=>{event.preventDefault();phone=$("#phone").value;const button=event.submitter;button.disabled=true;try{const result=await api("/v1/auth/otp/request",{method:"POST",body:JSON.stringify({phone})});challenge=result.challenge_token;$("#code-form").hidden=false;status($("#auth-status"),result.message);$("#code").focus()}catch(error){status($("#auth-status"),`请求失败：${error.message}`,true)}finally{button.disabled=false}});
$("#code-form").addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;try{await api("/v1/auth/otp/verify",{method:"POST",body:JSON.stringify({phone,challenge_token:challenge,code:$("#code").value})});await refresh()}catch(error){status($("#auth-status"),"验证码无效或已过期，请重试。",true)}finally{button.disabled=false}});
$("#upload-form").addEventListener("submit",async event=>{event.preventDefault();const file=$("#file").files[0];if(!file)return;const form=new FormData();form.append("purpose","question_image");form.append("file",file);const button=event.submitter;button.disabled=true;try{const uploaded=await api("/v1/files",{method:"POST",body:form,headers:{"Idempotency-Key":crypto.randomUUID()}});const task=await api("/v1/intakes",{method:"POST",body:JSON.stringify({file_id:uploaded.file_id}),headers:{"Idempotency-Key":crypto.randomUUID()}});status($("#upload-status"),`已保存，识别任务 ${task.task_id.slice(0,8)} 正在处理。`);await refresh()}catch(error){status($("#upload-status"),`上传失败：${error.message}。文件未丢失时可重试。`,true)}finally{button.disabled=false}});
$("#logout").addEventListener("click",async()=>{try{await api("/v1/session",{method:"DELETE"})}finally{show(false)}});refresh();
